### ISSUE TITLE
Html preprocecor

### ISSUE THREAD

**Issue by RESTOMAX** [nippur72/ifdef-loader#11]
Hi,

Is-it possible to preprocessing html files?

Exemple:

```
<!--#if dev-->
<div>DEVELOPMENT VERSION</div>
<!--#endif-->
```

Thanks for your job :)

**Comment by nippur72** [comment]
no, at the moment it's not possible because it is expecting to work with javascript files. 

To make it work with .html files, a whole different preprocessor is needed. It should be rather easy to write one, using the [cheerio](https://github.com/cheeriojs/cheerio) library. Perhaps making another different loader out of it.
