### ISSUE TITLE
Cannot use defines that have dashes

### ISSUE THREAD

**Issue by jgranick** [nippur72/ifdef-loader#15]
You cannot use defines that use dashes (similar to `ifdef-verbose`) because this doesn't evaluate as proper JavaScript:

```
/// #if my-custom-define
```

The Haxe language compiler converts `-D my-custom-define` to `#if my_custom_define` when evaluating source files, perhaps this would be a reasonable solution?

_Related issue:_

https://github.com/openfl/openfl/pull/1911

**Comment by nippur72** [comment]
so do you want to write 
```
/// #if my-custom-define
```
and have it turned into
```
/// #if my_custom_define
```
?

I don't think that is possible because what comes after the `#if` is meant to be generic JavaScript expression.

Can you please explain your use case? Why not just use `my_custom_define` from the beginning?

**Comment by nippur72** [comment]
I agree that the docs are not very clear. `ifdef-verbose` and `ifdef-triple-slash` are not actual symbols available for `#if`, they are special switches used to configure the tool itself. And that's why they have `-` in their names: name clashing with user defined symbols isn't possible because they ain't valid JavaScript identifiers.

**Comment by jgranick** [comment]
Oh yeah, I understand :smile:

I just mean, `ifdef-verbose` feels nice. `ifdef_verbose` feels a little funny. I don't think these defines (themselves) are necessary in other source files, but a quick sanitize on the define names might be nice and make this pattern valid
